// All UI text in one place — short labels; icons and Biggu carry most of the meaning.
export const t = {
  appName: 'Study with Biggu',
  tagline: 'Read · Remember · Recite',
  signIn: 'Sign in with Google',
  signOut: 'Sign out',
  notAllowed: "This account isn't on the list yet. Try another one.",
  lessons: 'My notes',
  newLesson: 'New note',
  firstLesson: 'Add your first note',
  parts: (n: number) => `${n} parts`,
  howToAdd: 'How do you want to add it?',
  paste: 'Paste text',
  file: 'PDF / Word',
  photo: 'Take photos',
  pastePlaceholder: 'Paste your note here…',
  pickedFiles: (n: number) => (n === 1 ? '1 file' : `${n} files`),
  addPhoto: 'Add photo',
  change: 'Change',
  makeParts: 'Split into parts',
  preparing: 'Biggu is reading your note…',
  preparingSlow: 'Long note — almost there…',
  fidelityWarning: 'Biggu may have left something out. Give it a quick check.',
  read: 'Read it',
  startSpeaking: 'Practice',
  listening: 'Biggu is listening…',
  connecting: 'Getting ready…',
  stuckTip: 'Stuck? Pause or tap Hint — Biggu will help.',
  hintButton: 'Hint',
  hintLimit: 'Hints',
  hintsTaken: (n: number) => (n === 0 ? 'No hints' : n === 1 ? '1 hint' : `${n} hints`),
  progress: 'Progress',
  noHistory: 'Recite this part to start tracking your progress.',
  best: 'Best',
  last: 'Last',
  triesLabel: 'Tries',
  newer: 'Newer',
  older: 'Older',
  pageOf: (n: number, total: number) => `${n} / ${total}`,
  editedSince: 'This part was edited after this try, so its words can’t be shown.',
  thinking: 'Biggu is thinking…',
  done: 'Done',
  scoring: 'Checking…',
  remembered: 'of the ideas',
  said: 'Got it',
  hinted: 'Hinted',
  missed: 'Missed',
  retry: 'Try again',
  edit: 'Edit',
  editPart: (n: number) => `Edit part ${n}`,
  partTitle: 'Title',
  richText: 'Rich text',
  markdown: 'Markdown',
  preview: 'Preview',
  save: 'Save',
  saving: 'Saving…',
  cancel: 'Cancel',
  feedbackQuestion: 'How was this session?',
  feedbackThanks: 'Thanks — Biggu will learn from this!',
  feedbackGood: 'Good session',
  feedbackBad: 'Something was off',
  feedbackWhat: 'What felt off?',
  feedbackReason: { score: 'Score felt wrong', heard: "Didn't hear me right", hints: "Hints weren't helpful", other: 'Something else' },
  feedbackCommentPlaceholder: 'Anything else? (optional)',
  feedbackSend: 'Send',
  admin: {
    title: 'Feedback',
    link: 'Feedback',
    total: 'Sessions',
    good: 'Good',
    off: 'Off',
    filters: { all: 'All', up: 'Good', down: 'Off', comment: 'With note' },
    download: 'Download JSONL',
    empty: 'No feedback here yet.',
    notAdmin: 'Only the admin can see this.',
    you: 'You',
    who: (email: string | null | undefined, uid: string) => email ?? `user ${uid.slice(0, 6)}`,
    transcript: 'What she said',
    noTranscript: '(nothing heard)',
    hints: 'Hints',
    hintAt: (s: number, manual: boolean) => `${s.toFixed(1)} s · ${manual ? 'tapped' : 'after a pause'}`,
    ideas: 'Ideas (Gemini grading)',
    words: 'Words',
    meta: 'Details',
    gradedBy: 'Graded by',
    models: 'Models',
    duration: 'Duration',
    hintLimit: 'Hint limit',
    noLimit: 'none',
  },
  updateReady: 'New version ready',
  update: 'Update',
  later: 'Later',
  rename: 'Rename note',
  renamePrompt: 'Note name',
  nextPart: 'Next part',
  allDone: 'Finish',
  back: 'Back',
  nextUp: 'Next up',
  deleteLesson: 'Delete this note',
  confirmDelete: 'Delete this note?',
  confirmDeleteBody: (title: string) => `“${title}” and all its scores will be gone for good.`,
  delete: 'Delete',
  more: 'More',
  part: (n: number, total: number) => `Part ${n} of ${total}`,
  error: 'Something went wrong. Try again.',
  micDenied: 'Biggu needs the microphone to hear you.',
  apiMissing: "The server isn't set up yet.",
  notFound: "Can't find this note.",
  tooBig: 'Too big (25 MB max).',
  unsupported: 'Use a PDF, Word file, photos or text.',
  cheer: (pct: number) =>
    pct >= 90 ? 'Amazing! 🎉' : pct >= 70 ? 'Great job!' : pct >= 40 ? 'Getting there!' : 'Read it once more, then try again!',
};
