// All UI text in one place — short labels; icons and Biggu carry most of the meaning.
export const t = {
  appName: 'Study with Biggu',
  tagline: 'Read · Remember · Recite',
  signIn: 'Sign in with Google',
  signOut: 'Sign out',
  notAllowed: "This account isn't on the list yet. Try another one.",
  lessons: 'My notes',
  newLesson: 'New note',
  firstLesson: 'Add your first note',
  parts: (n: number) => `${n} parts`,
  howToAdd: 'How do you want to add it?',
  paste: 'Paste text',
  file: 'PDF / Word',
  photo: 'Take photos',
  pastePlaceholder: 'Paste your note here…',
  pickedFiles: (n: number) => (n === 1 ? '1 file' : `${n} files`),
  addPhoto: 'Add photo',
  change: 'Change',
  makeParts: 'Split into parts',
  preparing: 'Biggu is reading your note…',
  preparingSlow: 'Long note, almost there…',
  fidelityWarning: 'Biggu may have left something out. Give it a quick check.',
  read: 'Read it',
  startSpeaking: 'Practice',
  listening: 'Biggu is listening…',
  connecting: 'Getting ready…',
  stuckTip: 'Stuck? Pause or tap Hint. Biggu will help.',
  hintButton: 'Hint',
  hintLimit: 'Hints',
  hintsTaken: (n: number) => (n === 0 ? 'No hints' : n === 1 ? '1 hint' : `${n} hints`),
  progress: 'Progress',
  noHistory: 'Recite this part to start tracking your progress.',
  best: 'Best',
  last: 'Last',
  triesLabel: 'Tries',
  newer: 'Newer',
  older: 'Older',
  pageOf: (n: number, total: number) => `${n} / ${total}`,
  editedSince: 'This part was edited after this try, so its words can’t be shown.',
  thinking: 'Biggu is thinking…',
  done: 'Done',
  scoring: 'Checking…',
  remembered: 'of the ideas',
  said: 'Got it',
  hinted: 'Hinted',
  missed: 'Missed',
  retry: 'Try again',
  edit: 'Edit',
  editPart: (n: number) => `Edit part ${n}`,
  partTitle: 'Title',
  richText: 'Rich text',
  markdown: 'Markdown',
  preview: 'Preview',
  save: 'Save',
  saving: 'Saving…',
  cancel: 'Cancel',
  feedbackQuestion: 'How was this session?',
  feedbackThanks: 'Thanks! Biggu will learn from this.',
  feedbackGood: 'Good session',
  feedbackBad: 'Something was off',
  feedbackWhat: 'What felt off?',
  feedbackReason: { score: 'Score felt wrong', heard: "Didn't hear me right", hints: "Hints weren't helpful", other: 'Something else' },
  feedbackCommentPlaceholder: 'Anything else? (optional)',
  feedbackSend: 'Send',
  tabNotes: 'My notes',
  tabExams: 'Exams',
  newExam: 'New exam',
  editExam: 'Edit exam',
  examName: "What's the exam?",
  examDate: 'When is it?',
  examNamePlaceholder: 'e.g. Bio midterm',
  whichNotes: 'Which notes are on it?',
  searchNotes: 'Search your notes',
  noNotesMatch: (q: string) => `No notes match “${q}”.`,
  noNotesYet: 'Add a note first, then make an exam from it.',
  pickHint: 'Tap a note to add it. Tap its parts count to pick only some parts.',
  allParts: (n: number) => `all ${n} parts`,
  someParts: (k: number, n: number) => `${k} of ${n} parts`,
  makeCramSheet: (notes: number) => `Make cram sheet · ${notes} ${notes === 1 ? 'note' : 'notes'}`,
  notesCount: (n: number) => `${n} ${n === 1 ? 'note' : 'notes'}`,
  daysTo: (d: number) => (d === 0 ? 'today' : d === 1 ? 'tomorrow' : d > 0 ? `in ${d} days` : 'done'),
  daysToGo: (d: number) => (d === 0 ? "It's today!" : d === 1 ? 'Tomorrow' : d > 0 ? `${d} days to go` : 'Exam done'),
  examNotFound: "Can't find this exam.",
  noExamsYet: 'No exams yet. Make one and Biggu will pick what to read right before it.',
  mostRelevant: 'Most relevant',
  mostImportant: 'Most important',
  sortBy: 'Sort',
  rememberThis: 'I remember this',
  cheers: [
    "You're doing pawsome!",
    'Biggu believes in you.',
    'Deep breath. You know more than you think.',
    'Purr-fect progress!',
    'One idea at a time. You got this.',
    'Stretch, sip some water, keep going!',
    'Every card makes you a little stronger.',
    'Biggu is so proud of you!',
    'Keep those paws moving, almost there!',
    'Hiss at the doubt. You are ready.',
    'Little steps add up to big wins.',
    'Smart cookie. Biggu would share his treats with you.',
  ],
  vporkNote: 'I love you ❤️ you can do it - Vpork',
  openPart: (source: string) => `Open ${source}`,
  cramSource: (note: string, part: number) => `${note} · Part ${part}`,
  giveMore: 'I have more time, give meow more!',
  allRead: "That's everything. You've got this!",
  cramEmpty: 'These parts have no words to read yet.',
  pickingIdeas: 'Biggu is picking what to read…',
  confirmDeleteExam: 'Delete this exam?',
  confirmDeleteExamBody: (title: string) => `“${title}” goes away. Your notes and scores stay.`,
  deleteExam: 'Delete exam',
  addToExam: 'Add to exam',
  addToExamTitle: 'Add to an exam',
  newExamWithNote: 'New exam with this note',
  noExamsToAdd: 'No exams yet.',
  admin: {
    title: 'Admin',
    tabs: { feedback: 'Feedback', usage: 'Usage' },
    total: 'Sessions',
    good: 'Good',
    off: 'Off',
    filters: { all: 'All', up: 'Good', down: 'Off', comment: 'With note' },
    download: 'Download JSONL',
    empty: 'No feedback here yet.',
    notAdmin: 'Only the admin can see this.',
    you: 'You',
    who: (email: string | null | undefined, uid: string) => email ?? `user ${uid.slice(0, 6)}`,
    transcript: 'What she said',
    noTranscript: '(nothing heard)',
    hints: 'Hints',
    hintAt: (s: number, manual: boolean) => `${s.toFixed(1)} s · ${manual ? 'tapped' : 'after a pause'}`,
    ideas: 'Ideas (Gemini grading)',
    words: 'Words',
    meta: 'Details',
    gradedBy: 'Graded by',
    models: 'Models',
    duration: 'Duration',
    hintLimit: 'Hint limit',
    noLimit: 'none',
    everyone: 'Everyone',
    sessions7: 'Sessions, 7 days',
    sessions30: 'Sessions, 30 days',
    activeDays: 'Active days, 30',
    avgScore: 'Avg score, 30 days',
    perDay: 'Sessions per day, last 30 days',
    perDayEmpty: 'No sessions in the last 30 days.',
    sessionsOn: (n: number, day: string) => `${n} session${n === 1 ? '' : 's'} · ${day}`,
    people: 'People',
    lastSeen: 'Last seen',
    opens: 'App opens',
    notes: 'Notes',
    parts: 'Parts',
    sessions: 'Sessions',
    avg: 'Avg score',
    never: '–',
    topParts: 'Most practiced parts',
    tries: (n: number) => `${n} tr${n === 1 ? 'y' : 'ies'}`,
    noProfile: 'Profile appears after their next app open',
  },
  updateReady: 'New version ready',
  update: 'Update',
  later: 'Later',
  rename: 'Rename note',
  renamePrompt: 'Note name',
  nextPart: 'Next part',
  allDone: 'Finish',
  back: 'Back',
  nextUp: 'Next up',
  deleteLesson: 'Delete this note',
  deletePart: 'Delete this part',
  confirmDeletePart: 'Delete this part?',
  confirmDeletePartBody: (title: string) => `“${title}” and its scores will be gone for good.`,
  confirmDelete: 'Delete this note?',
  confirmDeleteBody: (title: string) => `“${title}” and all its scores will be gone for good.`,
  delete: 'Delete',
  more: 'More',
  part: (n: number, total: number) => `Part ${n} of ${total}`,
  error: 'Something went wrong. Try again.',
  micDenied: 'Biggu needs the microphone to hear you.',
  apiMissing: "The server isn't set up yet.",
  notFound: "Can't find this note.",
  tooBig: 'Too big (25 MB max).',
  unsupported: 'Use a PDF, Word file, photos or text.',
  cheer: (pct: number) =>
    pct >= 90 ? 'Amazing! 🎉' : pct >= 70 ? 'Great job!' : pct >= 40 ? 'Getting there!' : 'Read it once more, then try again!',
};
