// All UI text in one place — short labels; icons and Biggu carry most of the meaning.
export const t = {
  appName: 'Study with Biggu',
  tagline: 'Read · Remember · Recite',
  signIn: 'Sign in with Google',
  signOut: 'Sign out',
  notAllowed: "This account isn't on the list yet. Try another one.",
  lessons: 'My notes',
  newLesson: 'New note',
  firstLesson: 'Add your first note',
  parts: (n: number) => `${n} parts`,
  howToAdd: 'How do you want to add it?',
  paste: 'Paste text',
  file: 'PDF / Word',
  photo: 'Take photos',
  pastePlaceholder: 'Paste your note here…',
  pickedFiles: (n: number) => (n === 1 ? '1 file' : `${n} files`),
  addPhoto: 'Add photo',
  change: 'Change',
  makeParts: 'Split into parts',
  preparing: 'Biggu is reading your note…',
  preparingSlow: 'Long note — almost there…',
  fidelityWarning: 'Biggu may have left something out. Give it a quick check.',
  read: 'Read it',
  startSpeaking: "I'm ready — recite",
  listening: 'Biggu is listening…',
  connecting: 'Getting ready…',
  stuckTip: 'Stuck? Pause or tap Hint — Biggu will help.',
  hintButton: 'Hint',
  hintLimit: 'Hints',
  hintsTaken: (n: number) => (n === 0 ? 'No hints' : n === 1 ? '1 hint' : `${n} hints`),
  progress: 'Progress',
  noHistory: 'Recite a part to start tracking your progress.',
  showAll: (n: number) => `Show all ${n}`,
  thinking: 'Biggu is thinking…',
  done: 'Done',
  scoring: 'Checking…',
  remembered: 'of the ideas',
  said: 'Got it',
  hinted: 'Hinted',
  missed: 'Missed',
  retry: 'Try again',
  edit: 'Edit',
  editPart: (n: number) => `Edit part ${n}`,
  partTitle: 'Title',
  richText: 'Rich text',
  markdown: 'Markdown',
  preview: 'Preview',
  save: 'Save',
  saving: 'Saving…',
  cancel: 'Cancel',
  rename: 'Rename note',
  renamePrompt: 'Note name',
  nextPart: 'Next part',
  allDone: 'Finish',
  back: 'Back',
  nextUp: 'Next up',
  deleteLesson: 'Delete this note',
  confirmDelete: 'Delete this note?',
  more: 'More',
  part: (n: number, total: number) => `Part ${n} of ${total}`,
  error: 'Something went wrong. Try again.',
  micDenied: 'Biggu needs the microphone to hear you.',
  apiMissing: "The server isn't set up yet.",
  notFound: "Can't find this note.",
  tooBig: 'Too big (25 MB max).',
  unsupported: 'Use a PDF, Word file, photos or text.',
  cheer: (pct: number) =>
    pct >= 90 ? 'Amazing! 🎉' : pct >= 70 ? 'Great job!' : pct >= 40 ? 'Getting there!' : 'Read it once more, then try again!',
};
